name: CI

on: [ push, pull_request ]

jobs:
  # rubocop linting
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec rubocop --parallel
